# Generated by Django 4.0.4 on 2022-05-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_name_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
